import type { Airport } from "@contracts/airports";

/**
 * Kopi av det kuraterte flyplassregisteret (contracts/airports.ts): kode, navn, by, land og registerets
 * «populær»-merke – det flyplassvelgeren viser med én gang. Appen henter bare typer fra contracts
 * (metro.config.js); verdier kopieres inn, som reisemålene. En test sammenligner kopien med registeret, så den
 * ikke kan skli fra.
 */
export type RegistryAirport = Pick<Airport, "iata" | "name" | "city" | "country" | "countryCode" | "popular">;

type Row = readonly [iata: string, name: string, city: string, country: string, countryCode: string, popular?: true];

const ROWS: readonly Row[] = [
  ["OSL", "Oslo lufthavn Gardermoen", "Oslo", "Norge", "NO", true],
  ["BGO", "Bergen lufthavn Flesland", "Bergen", "Norge", "NO", true],
  ["TRD", "Trondheim lufthavn Værnes", "Trondheim", "Norge", "NO", true],
  ["SVG", "Stavanger lufthavn Sola", "Stavanger", "Norge", "NO", true],
  ["TRF", "Sandefjord lufthavn Torp", "Sandefjord", "Norge", "NO", true],
  ["TOS", "Tromsø lufthavn", "Tromsø", "Norge", "NO", true],
  ["BOO", "Bodø lufthavn", "Bodø", "Norge", "NO"],
  ["AES", "Ålesund lufthavn Vigra", "Ålesund", "Norge", "NO"],
  ["KRS", "Kristiansand lufthavn Kjevik", "Kristiansand", "Norge", "NO"],
  ["HAU", "Haugesund lufthavn Karmøy", "Haugesund", "Norge", "NO"],
  ["MOL", "Molde lufthavn Årø", "Molde", "Norge", "NO"],
  ["EVE", "Harstad/Narvik lufthavn Evenes", "Evenes", "Norge", "NO"],
  ["LYR", "Svalbard lufthavn Longyear", "Longyearbyen", "Norge", "NO"],
  ["CPH", "København lufthavn Kastrup", "København", "Danmark", "DK", true],
  ["ARN", "Stockholm Arlanda flyplass", "Stockholm", "Sverige", "SE", true],
  ["GOT", "Göteborg Landvetter flygplats", "Göteborg", "Sverige", "SE"],
  ["HEL", "Helsingfors-Vanda flygplats", "Helsingfors", "Finland", "FI"],
  ["KEF", "Keflavík alþjóðaflugvöllur", "Reykjavík", "Island", "IS", true],
  ["LHR", "London Heathrow Airport", "London", "Storbritannia", "GB", true],
  ["LGW", "London Gatwick Airport", "London", "Storbritannia", "GB"],
  ["STN", "London Stansted Airport", "London", "Storbritannia", "GB"],
  ["MAN", "Manchester Airport", "Manchester", "Storbritannia", "GB"],
  ["EDI", "Edinburgh Airport", "Edinburgh", "Storbritannia", "GB"],
  ["CDG", "Paris Charles de Gaulle", "Paris", "Frankrike", "FR", true],
  ["ORY", "Paris Orly", "Paris", "Frankrike", "FR"],
  ["NCE", "Nice Côte d'Azur", "Nice", "Frankrike", "FR"],
  ["AMS", "Amsterdam Schiphol", "Amsterdam", "Nederland", "NL", true],
  ["FRA", "Frankfurt am Main", "Frankfurt", "Tyskland", "DE", true],
  ["MUC", "München", "München", "Tyskland", "DE"],
  ["BER", "Berlin Brandenburg", "Berlin", "Tyskland", "DE"],
  ["HAM", "Hamburg", "Hamburg", "Tyskland", "DE"],
  ["ZRH", "Zürich", "Zürich", "Sveits", "CH"],
  ["GVA", "Genève", "Genève", "Sveits", "CH"],
  ["VIE", "Wien", "Wien", "Østerrike", "AT"],
  ["MAD", "Madrid-Barajas", "Madrid", "Spania", "ES", true],
  ["BCN", "Barcelona-El Prat", "Barcelona", "Spania", "ES", true],
  ["AGP", "Málaga-Costa del Sol", "Málaga", "Spania", "ES", true],
  ["ALC", "Alicante-Elche", "Alicante", "Spania", "ES"],
  ["PMI", "Palma de Mallorca", "Palma", "Spania", "ES"],
  ["TFS", "Tenerife Sør", "Tenerife", "Spania", "ES"],
  ["LPA", "Gran Canaria", "Las Palmas", "Spania", "ES"],
  ["FCO", "Roma Fiumicino", "Roma", "Italia", "IT", true],
  ["MXP", "Milano Malpensa", "Milano", "Italia", "IT"],
  ["VCE", "Venezia Marco Polo", "Venezia", "Italia", "IT"],
  ["ATH", "Athen", "Athen", "Hellas", "GR"],
  ["LIS", "Lisboa Humberto Delgado", "Lisboa", "Portugal", "PT"],
  ["OPO", "Porto Francisco Sá Carneiro", "Porto", "Portugal", "PT"],
  ["FAO", "Faro", "Faro", "Portugal", "PT"],
  ["DUB", "Dublin", "Dublin", "Irland", "IE"],
  ["PRG", "Praha Václav Havel", "Praha", "Tsjekkia", "CZ"],
  ["WAW", "Warszawa Chopin", "Warszawa", "Polen", "PL"],
  ["KRK", "Kraków", "Kraków", "Polen", "PL"],
  ["BUD", "Budapest", "Budapest", "Ungarn", "HU"],
  ["IST", "Istanbul", "Istanbul", "Tyrkia", "TR", true],
  ["AYT", "Antalya", "Antalya", "Tyrkia", "TR", true],
  ["EBL", "Erbil internasjonale lufthavn", "Erbil", "Irak (Kurdistan-regionen)", "IQ", true],
  ["ISU", "Sulaymaniyah internasjonale lufthavn", "Sulaymaniyah", "Irak (Kurdistan-regionen)", "IQ", true],
  ["JED", "King Abdulaziz internasjonale lufthavn", "Jeddah", "Saudi-Arabia", "SA", true],
  ["BGW", "Bagdad internasjonale lufthavn", "Bagdad", "Irak", "IQ"],
  ["DAM", "Damaskus internasjonale lufthavn", "Damaskus", "Syria", "SY"],
  ["BEY", "Beirut Rafic Hariri", "Beirut", "Libanon", "LB", true],
  ["CMN", "Casablanca Mohammed V", "Casablanca", "Marokko", "MA", true],
  ["RAK", "Marrakech Menara", "Marrakech", "Marokko", "MA"],
  ["ASM", "Asmara internasjonale lufthavn", "Asmara", "Eritrea", "ER", true],
  ["ADD", "Addis Abeba Bole", "Addis Abeba", "Etiopia", "ET"],
  ["MGQ", "Mogadishu Aden Adde", "Mogadishu", "Somalia", "SO"],
  ["KBL", "Kabul internasjonale lufthavn", "Kabul", "Afghanistan", "AF", true],
  ["ISB", "Islamabad internasjonale lufthavn", "Islamabad", "Pakistan", "PK", true],
  ["LHE", "Lahore Allama Iqbal", "Lahore", "Pakistan", "PK"],
  ["KHI", "Karachi Jinnah", "Karachi", "Pakistan", "PK"],
  ["DAC", "Dhaka Hazrat Shahjalal", "Dhaka", "Bangladesh", "BD", true],
  ["CMB", "Colombo Bandaranaike", "Colombo", "Sri Lanka", "LK", true],
  ["GDN", "Gdańsk Lech Wałęsa", "Gdańsk", "Polen", "PL"],
  ["RIX", "Riga", "Riga", "Latvia", "LV"],
  ["TLL", "Tallinn", "Tallinn", "Estland", "EE"],
  ["VNO", "Vilnius", "Vilnius", "Litauen", "LT"],
  ["JFK", "New York JFK", "New York", "USA", "US", true],
  ["EWR", "Newark Liberty", "New York", "USA", "US"],
  ["LAX", "Los Angeles", "Los Angeles", "USA", "US", true],
  ["SFO", "San Francisco", "San Francisco", "USA", "US"],
  ["MIA", "Miami", "Miami", "USA", "US"],
  ["ORD", "Chicago O'Hare", "Chicago", "USA", "US"],
  ["BOS", "Boston Logan", "Boston", "USA", "US"],
  ["SEA", "Seattle-Tacoma", "Seattle", "USA", "US"],
  ["YYZ", "Toronto Pearson", "Toronto", "Canada", "CA"],
  ["YVR", "Vancouver", "Vancouver", "Canada", "CA"],
  ["CUN", "Cancún", "Cancún", "Mexico", "MX"],
  ["DXB", "Dubai", "Dubai", "Emiratene", "AE", true],
  ["DOH", "Doha Hamad", "Doha", "Qatar", "QA"],
  ["SIN", "Singapore Changi", "Singapore", "Singapore", "SG", true],
  ["BKK", "Bangkok Suvarnabhumi", "Bangkok", "Thailand", "TH", true],
  ["HKT", "Phuket", "Phuket", "Thailand", "TH"],
  ["HKG", "Hong Kong", "Hong Kong", "Hong Kong", "HK"],
  ["NRT", "Tokyo Narita", "Tokyo", "Japan", "JP", true],
  ["HND", "Tokyo Haneda", "Tokyo", "Japan", "JP"],
  ["ICN", "Seoul Incheon", "Seoul", "Sør-Korea", "KR"],
  ["DEL", "New Delhi", "New Delhi", "India", "IN", true],
  ["BOM", "Mumbai Chhatrapati Shivaji", "Mumbai", "India", "IN"],
  ["SYD", "Sydney Kingsford Smith", "Sydney", "Australia", "AU"],
  ["CPT", "Cape Town", "Cape Town", "Sør-Afrika", "ZA"],
  ["JNB", "Johannesburg OR Tambo", "Johannesburg", "Sør-Afrika", "ZA"],
  ["GRU", "São Paulo Guarulhos", "São Paulo", "Brasil", "BR"],
  ["EZE", "Buenos Aires Ezeiza", "Buenos Aires", "Argentina", "AR"],
];

export const REGISTRY: readonly RegistryAirport[] = ROWS.map(([iata, name, city, country, countryCode, popular]) => ({ iata, name, city, country, countryCode, ...(popular ? { popular } : {}) }));
