import type { Article } from "./types";

/**
 * Praktiske artikler: bagasje, billetter, pass, rettigheter.
 * Ingen tall for priser, gebyrer, visumkrav eller bagasjegrenser – de
 * endres, og leseren skal alltid sjekke kilden som faktisk bestemmer.
 */
export const PRACTICAL: Article[] = [
  {
    slug: "bagasje-slik-leser-du-billetten",
    title: "Bagasje: slik leser du hva som faktisk er inkludert",
    deck: "Tre ord som betyr helt forskjellige ting: inkludert, ikke inkludert og ikke oppgitt.",
    tags: ["bagasje", "billetter"],
    updated: "2026-09-07",
    relatedDestinations: ["istanbul", "erbil"],
    relatedArticles: ["handbagasje-det-som-overrasker", "hva-totalpris-betyr-hos-oss"],
    blocks: [
      { t: "p", text: "Den vanligste overraskelsen på flyplassen er ikke prisen på billetten, men prisen på kofferten. Grunnen er at «bagasje» ikke er én ting. Det er minst tre: det som kan tas med om bord, det som sjekkes inn, og det flyselskapet ikke har sagt noe om." },
      { t: "h2", id: "tre-tilstander", text: "De tre tilstandene" },
      { t: "ul", items: [
        "Inkludert: flyselskapet har oppgitt at et antall kolli følger billetten. Vi viser antallet per reisende.",
        "Ikke inkludert: flyselskapet har oppgitt at ingen kolli av denne typen følger med. Da kan du som regel kjøpe det til før betaling.",
        "Ikke oppgitt: flyselskapet har rett og slett ikke sendt oss informasjonen. Det betyr ikke at bagasje er gratis, og det betyr ikke at den mangler. Det betyr at du bør sjekke.",
      ] },
      { t: "p", text: "Hos HelloSky viser vi disse tre tilstandene hver for seg, både i søkeresultatet og i kassen. Vi gjetter aldri. Står det «ikke oppgitt», er det fordi kilden vår ikke har sagt det." },
      { t: "h2", id: "per-strekning", text: "Bagasjen gjelder per strekning" },
      { t: "p", text: "En reise med bytte kan ha ulike vilkår på ulike strekninger, særlig når to flyselskap deler reisen. Vi viser det laveste tallet som gjelder for hele reisen, slik at du ikke planlegger med en koffert som bare er med halvveis." },
      { t: "tip", title: "Før du betaler", text: "Sjekk bagasjelinjen i kassen én gang til. Der ser du hva som er inkludert, hva du har lagt til, og hva som er ukjent. Trenger du mer, er det billigere å legge til før avreise enn på flyplassen hos de fleste selskap." },
      { t: "h2", id: "vekt-og-mal", text: "Vekt og mål" },
      { t: "p", text: "Vi oppgir ikke vektgrenser som tall her, fordi de varierer fra selskap til selskap og endres uten forvarsel. Det som gjelder for akkurat din billett står i flyselskapets bagasjevilkår, og lenken finner du i bekreftelsen din. Reiser du med mye, som gaver til familien, er innsjekket kolli nesten alltid rimeligere enn overvekt." },
    ],
  },
  {
    slug: "handbagasje-det-som-overrasker",
    title: "Håndbagasje: det som oftest overrasker i sikkerhetskontrollen",
    deck: "Væsker, batterier og den lille ekstra vesken. Slik unngår du å pakke om på gulvet.",
    tags: ["bagasje"],
    updated: "2026-09-07",
    relatedDestinations: [],
    relatedArticles: ["bagasje-slik-leser-du-billetten", "reise-med-spedbarn"],
    blocks: [
      { t: "p", text: "Sikkerhetskontrollen er like på de fleste flyplasser i Europa, men den overrasker likevel. Nesten alltid på ett av tre punkter: væsker, elektronikk eller antall vesker." },
      { t: "h2", id: "vaesker", text: "Væsker" },
      { t: "p", text: "Hovedregelen er små beholdere i en gjennomsiktig pose som lukkes. Noen flyplasser har nye skannere som tillater mer, men reglene er ikke like overalt, og de kan skru dem tilbake. Pakk som om den strenge regelen gjelder, så slipper du å kaste noe. Morsmelk og medisiner har egne unntak; si fra i kontrollen." },
      { t: "h2", id: "batterier", text: "Batterier og elektronikk" },
      { t: "ul", items: [
        "Powerbanker og løse litiumbatterier skal i håndbagasjen, ikke i innsjekket koffert.",
        "Store elektroniske enheter må ofte tas ut av vesken i kontrollen.",
        "Enkelte land har egne regler for elektronikk på flyreiser ut av landet. Sjekk med flyselskapet før hjemreisen.",
      ] },
      { t: "h2", id: "antall", text: "Én eller to vesker?" },
      { t: "p", text: "Mange billetter gir plass til én liten veske under setet foran, og en større håndbagasje i hylla bare hvis den er inkludert eller kjøpt til. Vi viser skillet mellom «håndbagasje» og «innsjekket» i søket. Vær nøye med om det står ett eller to kolli før du pakker." },
      { t: "tip", text: "Ta med det du ikke kan miste i håndbagasjen: pass, medisiner, nøkler, ladere. Alt som tåler å komme dagen etter, kan sjekkes inn." },
      { t: "p", text: "Avinor har oppdaterte regler for norske flyplasser. Flyr du hjem fra en flyplass i utlandet, er det flyplassens og flyselskapets regler som gjelder på veien tilbake." },
    ],
  },
  {
    slug: "hva-totalpris-betyr-hos-oss",
    title: "Hva «totalpris» betyr hos HelloSky",
    deck: "Billettpris, skatter og vårt gebyr er med fra første søk. Her er hva som ikke kan være med.",
    tags: ["billetter"],
    updated: "2026-09-07",
    relatedDestinations: [],
    relatedArticles: ["bagasje-slik-leser-du-billetten", "nar-bor-du-bestille"],
    blocks: [
      { t: "p", text: "Prisen du ser i søkeresultatet er prisen for reisen slik flyselskapet har priset den, med skatter og avgifter, pluss vårt servicegebyr. Vi legger ikke på noe i kassen som ikke sto der først." },
      { t: "h2", id: "med", text: "Dette er med" },
      { t: "ul", items: [
        "Billettprisen fra flyselskapet for alle reisende du har valgt.",
        "Skatter og avgifter flyselskapet krever inn.",
        "HelloSky sitt servicegebyr, vist som egen linje.",
      ] },
      { t: "h2", id: "ikke-med", text: "Dette kan ikke være med" },
      { t: "p", text: "Ting du velger selv, kommer i tillegg: ekstra bagasje, setevalg og andre tilvalg. De vises som egne linjer når du legger dem til, før du betaler. Vi viser aldri en pris som endrer seg fordi du klikket videre." },
      { t: "h2", id: "endres", text: "Når prisen likevel endrer seg" },
      { t: "p", text: "Flyselskapene priser sekund for sekund. Sjelden, men av og til, er prisen vi hentet ikke lenger tilgjengelig når du bestiller. Da stopper vi og viser den nye prisen før noe belastes. Du velger om du vil fortsette." },
      { t: "tip", title: "«Fra»-priser på forsiden", text: "Prisene på forsiden og reisemålskortene er veiledende priser fra vårt eget prissøk for én voksen. De er ikke tilbud, og de er ikke garantert. Den ekte prisen for din reise ser du i søket." },
    ],
  },
  {
    slug: "navnet-pa-billetten",
    title: "Navnet på billetten må stemme med passet",
    deck: "Den ene regelen som ikke kan forhandles. Slik skriver du navn riktig, også når passet er annerledes enn hverdagsnavnet.",
    tags: ["billetter", "planlegging"],
    updated: "2026-09-07",
    relatedDestinations: [],
    relatedArticles: ["passet-gyldighet-og-barn", "reiser-du-alene-med-barn"],
    blocks: [
      { t: "p", text: "Flyselskapene sjekker navnet på billetten mot passet, og mange tillater ingen endringer etter at billetten er utstedt. Det som skjer ved feil, avhenger av selskapet: noen tar et gebyr, andre krever ny billett." },
      { t: "h2", id: "slik", text: "Slik fyller du ut" },
      { t: "ul", items: [
        "Bruk navnet nøyaktig som i passets maskinlesbare sone, den nederste linjen med tegnene <<<.",
        "Alle fornavn som står i passet, i samme rekkefølge.",
        "Bindestreker og apostrofer kan utelates hvis flyselskapet ikke godtar dem; bokstavene skal være de samme.",
        "Æ, Ø og Å skrives slik passet gjør det i den maskinlesbare sonen: AE, OE og AA.",
      ] },
      { t: "h2", id: "annet-navn", text: "Når passet har et annet navn enn du bruker" },
      { t: "p", text: "Mange i familiene vi reiser med har ett navn i hverdagen og et annet i passet, for eksempel farsnavn som mellomnavn eller et etternavn som endret seg etter giftermål. Billetten følger passet, alltid. Har du to pass, må billetten stemme med det passet du faktisk reiser på." },
      { t: "tip", title: "Lagre de reisende én gang", text: "I profilen kan du lagre navn og fødselsdato for de du reiser med, slik det står i passet. Da slipper du å skrive det på nytt, og feilen skjer ikke i farten." },
      { t: "p", text: "Oppdager du en feil etter bestilling, ta kontakt med oss med en gang. Jo tidligere, jo flere muligheter finnes." },
    ],
  },
  {
    slug: "passet-gyldighet-og-barn",
    title: "Passet: gyldighet, barn og det som ofte stopper folk",
    deck: "Mange land krever at passet er gyldig lenge etter hjemreisen. Sjekk det før du sjekker priser.",
    tags: ["planlegging", "familie"],
    updated: "2026-09-07",
    relatedDestinations: ["istanbul", "erbil", "beirut"],
    relatedArticles: ["navnet-pa-billetten", "reiser-du-alene-med-barn"],
    blocks: [
      { t: "p", text: "Den vanligste grunnen til at en reise ikke blir noe av, er ikke flyet. Det er passet. Enten er det utløpt, eller så er det gyldig, men ikke lenge nok for landet du skal til." },
      { t: "h2", id: "gyldighet", text: "Gyldighet etter hjemreise" },
      { t: "p", text: "Mange land krever at passet er gyldig i flere måneder etter at du har reist inn eller ut. Kravet varierer fra land til land, og det er landet du reiser til som bestemmer, ikke flyselskapet og ikke vi. Utenriksdepartementets reiseinformasjon for hvert land er stedet å sjekke. Flyselskapet kan nekte deg å gå om bord hvis passet ikke oppfyller kravet." },
      { t: "h2", id: "barn", text: "Barn har eget pass" },
      { t: "p", text: "Barn må ha eget pass, uansett alder. Barnepass har kortere gyldighet enn voksenpass, så det er lett å bli overrasket. Sjekk alle passene i familien samtidig, og bestill time hos politiet i god tid. Ventetiden varierer gjennom året." },
      { t: "h2", id: "to-pass", text: "Reiser du med to pass?" },
      { t: "p", text: "Har du både norsk pass og pass fra et annet land, kan du reise inn i det andre landet på det passet. Billetten må da stemme med det passet du viser ved innsjekk, og du bør vise samme pass ved utreise fra landet som ved innreise. Vær særlig oppmerksom på transittland, som kan ha egne krav." },
      { t: "tip", text: "Ta bilde av passene og legg det et sted du når fra telefonen. Mister du et pass på reisen, gjør kopien hjelpen fra ambassaden mye raskere." },
    ],
  },
  {
    slug: "reiser-du-alene-med-barn",
    title: "Reiser du alene med barn? Ta med samtykke",
    deck: "Noen land og noen flyselskap spør etter samtykke fra den andre forelderen. Det er enkelt å ha med og vanskelig å skaffe på flyplassen.",
    tags: ["familie", "planlegging"],
    updated: "2026-09-07",
    relatedDestinations: ["istanbul", "marrakech", "erbil"],
    relatedArticles: ["passet-gyldighet-og-barn", "mellomlanding-med-barn"],
    blocks: [
      { t: "p", text: "Reiser du med barn uten den andre forelderen, kan grensekontrollen i noen land be om dokumentasjon på at den andre forelderen samtykker. Det samme gjelder besteforeldre, tanter og onkler som reiser med barnebarn eller nevøer." },
      { t: "h2", id: "hva", text: "Hva du bør ha med" },
      { t: "ul", items: [
        "Et signert samtykke fra den forelderen som ikke er med, med navn, fødselsdato og reiseperiode.",
        "Kopi av den fraværende forelderens pass eller legitimasjon.",
        "Dokumentasjon på foreldreansvar hvis du har det alene, for eksempel fra folkeregisteret.",
        "Fødselsattest for barnet hvis dere ikke har samme etternavn.",
      ] },
      { t: "p", text: "Noen land krever at samtykket er attestert eller oversatt. Reglene står hos landets ambassade i Norge, og det er der du får det endelige svaret. Spør i god tid; svaret kan ta noen dager." },
      { t: "h2", id: "flyselskap", text: "Flyselskapet kan også spørre" },
      { t: "p", text: "Selv om landet ikke krever det, kan flyselskapet be om samtykke ved innsjekk, fordi de er ansvarlige for at passasjerene slipper inn ved ankomst. Har du papirene i håndbagasjen, er det ferdig snakket." },
      { t: "tip", title: "Barn som reiser helt alene", text: "Barn uten voksen om bord må som regel reise med flyselskapets eskorteordning, som bestilles direkte hos selskapet og har egne aldersgrenser. Ta kontakt med oss før du bestiller, så finner vi ut hva som gjelder for ruten." },
    ],
  },
  {
    slug: "forsinket-eller-innstilt",
    title: "Forsinket eller innstilt: rettighetene dine i korte trekk",
    deck: "Hva du kan forvente, hvem som skal hjelpe deg, og hva du bør ta vare på.",
    tags: ["billetter"],
    updated: "2026-09-07",
    relatedDestinations: [],
    relatedArticles: ["mellomlanding-flyplassbytte", "hva-totalpris-betyr-hos-oss"],
    blocks: [
      { t: "p", text: "Når flyet er forsinket eller innstilt, er det flyselskapet som er ansvarlig for å ta deg til bestemmelsesstedet og for å hjelpe deg underveis. HelloSky hjelper deg med å finne ut hva som gjelder og med å ta kontakt, men det er flyselskapet som utfører transporten." },
      { t: "h2", id: "eu", text: "Reiser fra EU/EØS" },
      { t: "p", text: "Flyr du fra en flyplass i EU/EØS, eller med et EU/EØS-selskap inn til EU/EØS, gjelder felles europeiske regler for forpleining, ombooking og i noen tilfeller kompensasjon. Beløpene avhenger av avstand og forsinkelse, og det finnes unntak for ekstraordinære omstendigheter som vær. Luftfartstilsynet og Forbrukerrådet forklarer reglene på norsk, og de er oppdaterte." },
      { t: "h2", id: "utenfor", text: "Reiser utenfor EU/EØS" },
      { t: "p", text: "Flyr du hjem fra et land utenfor EU/EØS med et selskap som ikke er europeisk, er det flyselskapets egne vilkår som gjelder. De er ofte mindre generøse. Sjekk hva selskapet tilbyr før du takker ja til noe." },
      { t: "h2", id: "gjor", text: "Dette bør du gjøre" },
      { t: "steps", items: [
        { title: "Be om det skriftlig", text: "Få forsinkelsen eller innstillingen bekreftet av flyselskapet, på papir eller e-post." },
        { title: "Ta vare på kvitteringer", text: "Mat, hotell og transport som skyldes forsinkelsen kan du kreve dekket hvis reglene gir rett til det." },
        { title: "Ikke bestill ny billett selv uten å spørre", text: "Ombooking skal som hovedregel gjøres av flyselskapet. Kjøper du ny billett på egen hånd, er det ikke sikkert du får den dekket." },
        { title: "Kontakt oss", text: "Vi ser bestillingen din, og kan hjelpe deg å nå flyselskapet og finne alternativer." },
      ] },
      { t: "tip", text: "Meld deg på flyvarsler i profilen. Da får du beskjed om endringer på e-post så snart vi får dem fra flyselskapet." },
    ],
  },
  {
    slug: "nar-bor-du-bestille",
    title: "Når bør du bestille? Ærlig svar om tid og pris",
    deck: "Det finnes ingen magisk dag. Men det finnes mønstre, og de handler mest om ferier og høytider.",
    tags: ["billetter", "planlegging"],
    updated: "2026-09-07",
    relatedDestinations: ["istanbul", "erbil", "islamabad"],
    relatedArticles: ["reise-hjem-til-hoytidene", "hva-totalpris-betyr-hos-oss"],
    blocks: [
      { t: "p", text: "Vi får spørsmålet hver dag: er det billigere å bestille tidlig, eller vente? Vi kan ikke gi deg en dato, for den finnes ikke. Prisene settes av flyselskapene etter hvor mange seter som er igjen, og det endrer seg time for time." },
      { t: "h2", id: "monstre", text: "Mønstrene vi faktisk ser" },
      { t: "ul", items: [
        "Perioder mange vil reise samtidig er dyre: skoleferier, jul, Eid, Newroz og sommeren. Der lønner det seg nesten alltid å være tidlig ute, fordi setene tar slutt.",
        "Utenfor ferier finnes det ofte flere seter og mer bevegelse i pris begge veier.",
        "Direkteruter med få avganger i uken fylles fortere enn ruter med mange daglige avganger.",
        "Siste uken før avreise er sjelden billig på ruter hjem, fordi de som må reise, reiser uansett.",
      ] },
      { t: "h2", id: "fleksibel", text: "Fleksibilitet er den største rabatten" },
      { t: "p", text: "Kan du reise en dag før eller etter, eller fra en annen flyplass, er det ofte der de store forskjellene ligger. I søket viser vi priser for dagene rundt datoen din, og du kan sortere etter det som er viktigst for deg." },
      { t: "h2", id: "vent", text: "Vet du hvor, men ikke når?" },
      { t: "p", text: "Sett opp en prisovervåking. Du forteller oss ruten, perioden og hva du maks vil betale, så sjekker vi ekte priser jevnlig og sier fra når noe passer. Vi sier bare fra når prisen faktisk finnes, med gebyrer regnet inn." },
      { t: "tip", text: "Reiser dere flere? Søk med riktig antall reisende fra start. Prisen for fem seter er ikke alltid fem ganger prisen for ett." },
    ],
  },
];
