import type { Article } from "./types";

/** Familie, mellomlandinger og lange turer: det HelloSky faktisk kan best. */
export const FAMILY: Article[] = [
  {
    slug: "mellomlanding-med-barn",
    title: "Mellomlanding med barn: det som gjør den enkel",
    deck: "Lengden er ikke det viktigste. Det er om dere må bytte terminal, hente bagasje, eller løpe.",
    tags: ["familie", "mellomlanding"],
    updated: "2026-09-07",
    hero: "istanbul",
    relatedDestinations: ["istanbul", "erbil", "islamabad"],
    relatedArticles: ["mellomlanding-flyplassbytte", "lang-flytur-med-familien", "istanbul-to-flyplasser"],
    searchIata: "IST",
    blocks: [
      { t: "p", text: "En mellomlanding på to timer kan være rolig eller kaotisk. Forskjellen ligger nesten aldri i klokken, men i hva som skjer mellom flyene. Derfor ser vi på mer enn tiden når vi rangerer reiser som «familievennlige»." },
      { t: "h2", id: "sjekk", text: "Fire ting å sjekke før du velger" },
      { t: "ul", items: [
        "Samme flyplass? Et bytte mellom to flyplasser i samme by er en helt annen reise, med transport, ny sikkerhetskontroll og ofte ny innsjekk.",
        "Gjennomgående bagasje? Med én billett hos samme selskap eller partnere sendes bagasjen som regel helt fram. Med to separate billetter må du hente og sjekke inn på nytt.",
        "Nok tid, men ikke for mye. Med barn er halvannen til tre timer ofte det behagelige. Vi viser tiden på hver mellomlanding i søket.",
        "Ankomst om natten? En mellomlanding klokka tre om natten med små barn er sjelden verdt en liten prisforskjell.",
      ] },
      { t: "h2", id: "under", text: "Under mellomlandingen" },
      { t: "p", text: "Finn neste gate først, så mat. Store flyplasser som Istanbul har lekeområder og familierom; spør ved informasjonen. Fyll vannflasker etter sikkerhetskontrollen, og ha én liten pose med det barna trenger de neste tre timene lett tilgjengelig, så du slipper å pakke ut hele håndbagasjen." },
      { t: "h2", id: "vogn", text: "Barnevogn" },
      { t: "p", text: "De fleste selskap lar deg ta vognen til flydøren og gir den tilbake enten ved døren eller ved bagasjebåndet. Hvor du får den igjen på mellomlandingen, varierer. Spør ved innsjekk, og be uttrykkelig om å få den ved døren hvis dere har lang vei mellom gatene." },
      { t: "tip", title: "Familievennlig i søket", text: "Velg «Familievennlig» over søkeresultatene. Da rangerer vi først på færre stopp, kortere ventetid og ingen flyplassbytte, og deretter på pris." },
    ],
  },
  {
    slug: "reise-med-spedbarn",
    title: "Reise med spedbarn: billett, sete og det praktiske",
    deck: "Barn under to år reiser oftest på fanget. Her er det du bør vite før du bestiller.",
    tags: ["familie"],
    updated: "2026-09-07",
    relatedDestinations: ["istanbul", "beirut"],
    relatedArticles: ["mellomlanding-med-barn", "lang-flytur-med-familien", "passet-gyldighet-og-barn"],
    blocks: [
      { t: "p", text: "Et spedbarn på flyet trenger sin egen billett, selv om det sitter på fanget. I søket vårt velger du «spedbarn» som egen reisende, så vises prisen med barnet inkludert." },
      { t: "h2", id: "fang-eller-sete", text: "På fanget eller eget sete?" },
      { t: "p", text: "Barn under to år kan som regel reise på fanget til en lav pris. På lange turer velger mange likevel å kjøpe et eget sete til barnet og bruke godkjent bilsete om bord. Det koster mer, men gir søvn til alle. Hvilke bilseter som er godkjent, bestemmer flyselskapet." },
      { t: "h2", id: "toarsdagen", text: "Fyller barnet to år på reisen?" },
      { t: "p", text: "Alderen regnes på hver strekning. Er barnet under to år på utreisen og over to på hjemreisen, må hjemreisen bestilles som barn med eget sete. Vi ber om fødselsdato i søket nettopp for å håndtere dette riktig." },
      { t: "h2", id: "om-bord", text: "Om bord" },
      { t: "ul", items: [
        "Babyseng ved skottet finnes på mange lange ruter og kan ofte bestilles på forhånd hos flyselskapet. Vekt- og aldersgrenser gjelder.",
        "Morsmelk, morsmelkerstatning og barnemat har egne unntak fra væskereglene. Si fra i sikkerhetskontrollen.",
        "Barnevogn og bilsete kan som regel sjekkes inn i tillegg til bagasjen, ofte uten ekstra kostnad. Sjekk selskapets vilkår.",
      ] },
      { t: "tip", text: "Pakk én skift til deg selv i håndbagasjen, ikke bare til barnet. De som har prøvd, vet hvorfor." },
    ],
  },
  {
    slug: "lang-flytur-med-familien",
    title: "Lang flytur med familien: seter, mat og søvn",
    deck: "Seks timer eller mer med barn er helt overkommelig når tre ting er på plass før avreise.",
    tags: ["familie", "planlegging"],
    updated: "2026-09-07",
    hero: "islamabad",
    relatedDestinations: ["islamabad", "delhi", "dhaka", "colombo"],
    relatedArticles: ["mellomlanding-med-barn", "reise-med-spedbarn"],
    blocks: [
      { t: "p", text: "Reisene til Islamabad, Delhi, Dhaka og Colombo er lange, og ofte med ett bytte. Det som skiller en god tur fra en slitsom, avgjøres før dere drar hjemmefra." },
      { t: "h2", id: "seter", text: "Seter" },
      { t: "p", text: "Sitt sammen. Det høres opplagt ut, men på fulle fly er det ikke gitt. Mange selskap lar familier med små barn velge seter uten ekstra kostnad, andre tar betalt. Vi viser setevalg i kassen der flyselskapet tilbyr det. Velg rader nær hverandre heller enn én rad med gangplass langt unna resten." },
      { t: "h2", id: "mat", text: "Mat" },
      { t: "p", text: "Barnemeny må ofte bestilles hos flyselskapet i forkant, gjerne et døgn før avreise. Ta med snacks barna faktisk liker; det som serveres, er ikke alltid det. Halal- og vegetarmenyer finnes på de fleste lange ruter, men også de må forhåndsbestilles." },
      { t: "h2", id: "sovn", text: "Søvn" },
      { t: "ul", items: [
        "Nattfly er ofte lettest med barn som sover lett, og tyngst med barn som ikke gjør det. Du kjenner dine.",
        "Ta med noe kjent: kosedyr, en tynn pledd, hodetelefoner som passer barn.",
        "Skjermtid på fly er ikke en fallitt. Last ned før avreise; nettet om bord er sjelden godt nok.",
      ] },
      { t: "h2", id: "ankomst", text: "Ankomst" },
      { t: "p", text: "Planlegg ingenting den første dagen. Tidsforskjell og lite søvn slår hardest ut på de minste. Har familien mulighet til å hente på flyplassen, er det verdt mer enn noen annen bekvemmelighet på turen." },
      { t: "tip", title: "Lagre reisende", text: "Med reisende lagret i profilen går bestillingen fort, også med fem pass og fem fødselsdatoer." },
    ],
  },
  {
    slug: "mellomlanding-flyplassbytte",
    title: "Når mellomlandingen egentlig er et flyplassbytte",
    deck: "London, Paris, Istanbul og Milano har flere flyplasser. Et bytte mellom dem er en reise i seg selv.",
    tags: ["mellomlanding", "storby"],
    updated: "2026-09-07",
    relatedDestinations: ["london", "paris", "istanbul"],
    relatedArticles: ["mellomlanding-med-barn", "istanbul-to-flyplasser", "forsinket-eller-innstilt"],
    blocks: [
      { t: "p", text: "Et søkeresultat kan se ut som én reise med ett stopp, men koden forteller mer. Lander du på én flyplass og drar fra en annen, står det tydelig i søket vårt som «flyplassbytte», fordi det endrer alt." },
      { t: "h2", id: "hva-det-betyr", text: "Hva et bytte innebærer" },
      { t: "ul", items: [
        "Du må hente bagasjen, ta transport mellom flyplassene og sjekke inn på nytt.",
        "Du må gjennom ny sikkerhetskontroll og eventuelt ny passkontroll.",
        "Er reisen på to separate billetter, er den andre billetten din risiko hvis den første er forsinket.",
        "Noen land krever visum for å forlate transittområdet, selv for et flyplassbytte.",
      ] },
      { t: "h2", id: "byene", text: "Byene der det skjer oftest" },
      { t: "p", text: "London har flere flyplasser med lang vei mellom. Paris har to store. Istanbul har én på den europeiske og én på den asiatiske siden, og reisen mellom dem kan ta lang tid i trafikk. Milano, Stockholm, Roma og New York er andre eksempler." },
      { t: "h2", id: "unnga", text: "Slik unngår du det" },
      { t: "p", text: "Velg «Korte mellomlandinger» eller «Familievennlig» i søket; begge holder flyplassbytter nederst. Og les mellomlandingslinjen under hver reise. Der står flyplassen for ankomst og avgang, og tiden mellom." },
      { t: "tip", text: "Er byttet uunngåelig, regn med mye mer tid enn du tror, og velg én billett gjennom hele reisen når det finnes. Da er flyselskapet ansvarlig for å få deg fram hvis første fly er forsinket." },
    ],
  },
  {
    slug: "helgetur-fredag-ut-sondag-hjem",
    title: "Helgetur: fredag ut, søndag hjem",
    deck: "To netter er nok når du velger riktig by, riktig flyplass og riktig avgangstid.",
    tags: ["helg", "storby"],
    updated: "2026-09-07",
    hero: "london",
    relatedDestinations: ["london", "paris", "barcelona", "lisboa", "rome"],
    relatedArticles: ["storby-forste-gang", "mellomlanding-flyplassbytte"],
    blocks: [
      { t: "p", text: "En helgetur lykkes eller mislykkes på flyplassene. Ikke på hotellet, ikke på været. Velger du en by med kort vei fra flyplassen til sentrum og fly som passer arbeidsdagen, får du nesten to hele dager ut av to netter." },
      { t: "h2", id: "byer", text: "Byer som fungerer på to netter" },
      { t: "ul", items: [
        "London: mange avganger fra Norge, og godt kollektivtilbud fra alle flyplassene. Sjekk hvilken flyplass du lander på; reisetiden inn til byen varierer mye.",
        "Paris: både sentralt og lett å ta seg rundt i. Første kveld kan brukes.",
        "Barcelona og Lisboa: kort vei fra flyplassen, og en helg holder til mer enn du tror.",
        "Roma: perfekt for to netter hvis du velger ett område og blir der.",
      ] },
      { t: "h2", id: "tid", text: "Tider som gir mest" },
      { t: "p", text: "Fredag ettermiddag ut og søndag kveld hjem gir to hele dager. Vi setter søket til neste fredag når du klikker på helgeideene på forsiden, så kan du flytte datoene selv. Sjekk også lørdag morgen: noen ganger er den avgangen både billigere og roligere." },
      { t: "h2", id: "bagasje", text: "Bare håndbagasje" },
      { t: "p", text: "For to netter er håndbagasje nok for de fleste. Sjekk at billetten inkluderer den størrelsen du trenger; noen billettyper gir bare plass til én liten veske. Vi viser hva som er med, per billett." },
      { t: "tip", text: "Lagre reisemålet, så ligger det under Lagret når helgen nærmer seg. Og sett gjerne en prisovervåking for «kun helger» på ruten du drømmer om." },
    ],
  },
  {
    slug: "storby-forste-gang",
    title: "Storby første gang: London, Paris, Roma",
    deck: "Det som sparer tid i tre av Europas største byer, fra flyplassen til middagen.",
    tags: ["storby", "forste-gang"],
    updated: "2026-09-07",
    hero: "paris",
    relatedDestinations: ["london", "paris", "rome"],
    relatedArticles: ["helgetur-fredag-ut-sondag-hjem", "handbagasje-det-som-overrasker"],
    blocks: [
      { t: "p", text: "Første gang i en stor by går mesteparten av tiden med til å finne ut hvordan byen fungerer. Her er det som sparer tid i tre byer vi sender mange til." },
      { t: "h2", id: "london", text: "London" },
      { t: "ul", items: [
        "Kollektivtransport betales med kontaktløst kort eller telefon direkte ved sperringene. Du trenger ikke kjøpe billett på forhånd.",
        "Museene i byen har ofte gratis inngang til hovedsamlingene. Populære utstillinger og attraksjoner må bookes på nett.",
        "Fra flyplassen: tog og ekspresstog er raskest, buss er billigst. Velg etter hvor du bor.",
      ] },
      { t: "h2", id: "paris", text: "Paris" },
      { t: "ul", items: [
        "Metroen dekker det meste, og billetter kjøpes i automat eller app. Sjekk hva som gjelder for turen fra flyplassen; den har egen pris.",
        "Store attraksjoner krever ofte tidsbestilling på nett. Uten det kan køen ta halve dagen.",
        "Byen er gåbar. Velg ett eller to områder per dag i stedet for å krysse byen flere ganger.",
      ] },
      { t: "h2", id: "roma", text: "Roma" },
      { t: "ul", items: [
        "Fra flyplassen finnes både tog og buss til sentrum. Toget er mest forutsigbart i rushtiden.",
        "De mest kjente stedene krever forhåndsbestilling i høysesong. Bestill før du reiser.",
        "Byen fungerer best til fots. Gode sko slår alle apper.",
      ] },
      { t: "tip", text: "Ta bilde av hotellets adresse og nærmeste stasjon før du lander. Det sparer deg for den første, forvirrede halvtimen." },
    ],
  },
  {
    slug: "reise-hjem-til-hoytidene",
    title: "Reise hjem til høytidene: Eid, Newroz, jul",
    deck: "De ukene alle vil reise samtidig. Slik planlegger du så det ikke koster mer enn det må.",
    tags: ["planlegging", "familie", "kurdistan", "midtosten"],
    updated: "2026-09-07",
    hero: "erbil",
    relatedDestinations: ["erbil", "sulaymaniyah", "istanbul", "islamabad", "marrakech"],
    relatedArticles: ["nar-bor-du-bestille", "passet-gyldighet-og-barn", "bagasje-slik-leser-du-billetten"],
    blocks: [
      { t: "p", text: "Rundt høytidene reiser alle samtidig, i samme retning, til de samme byene. Setene tar slutt, prisene stiger, og de som venter, ender med å reise dagen etter festen. Det finnes ingen triks, men det finnes planlegging." },
      { t: "h2", id: "datoer", text: "Datoene flytter seg" },
      { t: "p", text: "Eid følger månekalenderen og flytter seg hvert år. Newroz er rundt vårjevndøgn. Jul og nyttår er faste, men treffer skoleferien. Sjekk datoene for året du skal reise, og regn med at dagene rett før og rett etter er de dyreste." },
      { t: "h2", id: "planen", text: "Planen som fungerer" },
      { t: "steps", items: [
        { title: "Bestem hvem som reiser", text: "Sjekk passene til alle, også barna, før du ser på priser. Utløpt pass er den vanligste grunnen til at planen ryker." },
        { title: "Søk tidlig, med riktig antall", text: "Søk med hele familien fra start. Fem seter på samme fly er ikke alltid tilgjengelig på det billigste nivået." },
        { title: "Vær fleksibel på dato, ikke på rute", text: "Én dag før eller etter kan gjøre stor forskjell. En helt annen rute med to bytter er sjelden verdt det med barn." },
        { title: "Sett prisovervåking", text: "Vet du perioden, men ikke dagen? La oss sjekke prisene for deg og si fra når noe passer." },
      ] },
      { t: "h2", id: "gaver", text: "Bagasjen hjem" },
      { t: "p", text: "Gaver veier. Innsjekket kolli du legger til før avreise, koster nesten alltid mindre enn overvekt på flyplassen. Vi viser bagasjen per billett i søket; velg «Ekstra bagasje» som det viktigste, så rangerer vi etter det." },
      { t: "tip", text: "Hjemreisen etter høytiden er ofte like full som utreisen. Bestill begge veier samtidig." },
    ],
  },
];
