import type { Article } from "./types";

/**
 * Steder: det praktiske rundt ankomst og flyplass. Aldri visumregler eller
 * priser som tall – vi peker på UD og ambassaden, som faktisk bestemmer.
 */
export const PLACES: Article[] = [
  {
    slug: "istanbul-to-flyplasser",
    title: "Istanbul har to flyplasser. Det betyr noe for deg",
    deck: "Den ene ligger på den europeiske siden, den andre på den asiatiske. Velg etter hvor familien bor.",
    tags: ["midtosten", "mellomlanding", "storby"],
    updated: "2026-09-07",
    hero: "istanbul",
    relatedDestinations: ["istanbul"],
    relatedArticles: ["mellomlanding-flyplassbytte", "mellomlanding-med-barn"],
    searchIata: "IST",
    blocks: [
      { t: "p", text: "Istanbul Airport (IST) ligger på den europeiske siden, nord for byen. Sabiha Gökçen (SAW) ligger på den asiatiske siden. Begge er store, begge har ruter til Norge, og reisen mellom dem går tvers gjennom en by med mye trafikk." },
      { t: "h2", id: "velg", text: "Velg flyplass etter adresse, ikke pris" },
      { t: "p", text: "Bor familien på den asiatiske siden, kan en litt dyrere billett til SAW spare dere for timer i bil. Bor de på den europeiske siden, gjelder det motsatte. Søk gjerne begge; i søket kan du velge «Istanbul (alle)» eller én bestemt flyplass." },
      { t: "h2", id: "videre", text: "Reiser du videre?" },
      { t: "p", text: "Istanbul er et av de største knutepunktene for reiser videre til Kurdistan-regionen, Midtøsten og Asia. Mellomlanding på samme flyplass med én billett er som regel enkelt. Et bytte mellom IST og SAW er derimot et flyplassbytte, og vi viser det tydelig i søket." },
      { t: "h2", id: "praktisk", text: "Praktisk ved ankomst" },
      { t: "ul", items: [
        "Begge flyplassene har taxi, buss og forhåndsbestilt transport. Taxi bruker taksameter; be om det.",
        "Passkontroll kan ta tid i høysesong. Regn med det hvis noen skal hente dere.",
        "Sjekk innreisereglene for Tyrkia hos Utenriksdepartementet før avreise, også hvis du har reist mange ganger. Kravene til passets gyldighet er strengere enn i mange andre land.",
      ] },
      { t: "tip", text: "Har du to pass, må billetten stemme med det passet du viser ved innsjekk i Norge. Reis inn og ut av Tyrkia på samme pass." },
    ],
  },
  {
    slug: "erbil-forste-gang",
    title: "Første gang til Erbil: det praktiske",
    deck: "Flyplassen, ankomsten og det du bør ha ordnet før du drar.",
    tags: ["kurdistan", "forste-gang"],
    updated: "2026-09-07",
    hero: "erbil",
    relatedDestinations: ["erbil", "sulaymaniyah"],
    relatedArticles: ["sulaymaniyah-eller-erbil", "reise-hjem-til-hoytidene", "passet-gyldighet-og-barn"],
    searchIata: "EBL",
    blocks: [
      { t: "p", text: "Erbil er den ruten vi sender flest til, og den vi kjenner best. Flyplassen ligger like utenfor byen, og de fleste flyr dit via Istanbul, Wien, Doha eller Dubai. Direkteruter finnes i perioder; de dukker opp i søket når de går." },
      { t: "h2", id: "for", text: "Før du drar" },
      { t: "ul", items: [
        "Innreise: Kurdistan-regionen har egne ordninger, og reglene endres. Sjekk Utenriksdepartementets reiseinformasjon for Irak og regionens offisielle kanaler før du bestiller, ikke etter.",
        "Passet: mange land krever gyldighet i flere måneder etter hjemreise. Sjekk kravet, ikke bare utløpsdatoen.",
        "Bagasje: gaver veier. Legg til kolli før avreise hvis billetten ikke inkluderer nok.",
      ] },
      { t: "h2", id: "ankomst", text: "Ankomst" },
      { t: "p", text: "Flyplassen i Erbil har en egen ordning der de som henter, venter ved et eget terminalområde og passasjerene fraktes ut med buss fra hovedterminalen. Si fra til dem som henter deg hvor de skal vente. Det tar litt tid; ikke bli urolig om det går en halvtime fra landing til dere møtes." },
      { t: "h2", id: "arstid", text: "Årstid" },
      { t: "p", text: "Sommeren er svært varm, vinteren kald og av og til våt. Newroz i mars og Eid er de travleste ukene, både i prisen på billetten og på flyplassen. Planlegger du å reise da, er tidlig bestilling det som faktisk hjelper." },
      { t: "tip", title: "Vi svarer på kurdisk og norsk", text: "Ring eller skriv til oss om du lurer på noe om ruten. Vi har reist den selv." },
    ],
  },
  {
    slug: "sulaymaniyah-eller-erbil",
    title: "Sulaymaniyah eller Erbil: hvilken flyplass?",
    deck: "Begge har fly fra Europa. Den riktige avhenger av hvor du skal, og hva som går den dagen.",
    tags: ["kurdistan", "planlegging"],
    updated: "2026-09-07",
    hero: "sulaymaniyah",
    relatedDestinations: ["sulaymaniyah", "erbil"],
    relatedArticles: ["erbil-forste-gang", "mellomlanding-med-barn"],
    searchIata: "ISU",
    blocks: [
      { t: "p", text: "Erbil (EBL) og Sulaymaniyah (ISU) ligger noen timers kjøring fra hverandre. Erbil har flest avganger; Sulaymaniyah har færre, men sparer deg for kjøreturen hvis det er dit du skal." },
      { t: "h2", id: "regn", text: "Regn på hele reisen" },
      { t: "p", text: "En billigere billett til Erbil pluss bil til Sulaymaniyah er ikke alltid billigere når du regner inn timer, bensin eller taxi, og en trøtt familie. Søk begge flyplassene og sammenlign totalen, ikke bare flybilletten." },
      { t: "h2", id: "tilbud", text: "Hva som går" },
      { t: "ul", items: [
        "Sulaymaniyah har færre ukentlige avganger. Er datoen låst, kan det være at bare Erbil passer.",
        "Ruter og selskaper endres gjennom året. Søket viser det som faktisk finnes på datoen din.",
        "Reiser dere flere, kan det lønne seg å se på begge flyplassene for både ut- og hjemreise, og blande.",
      ] },
      { t: "h2", id: "sammenlign", text: "Sammenlign i søket" },
      { t: "p", text: "Marker to reiser i søkeresultatet og trykk «Sammenlign». Da ser du pris, reisetid, mellomlandinger og bagasje side om side, med gebyrer regnet inn." },
      { t: "tip", text: "Innreisereglene er de samme for begge flyplassene, men sjekk dem likevel hos Utenriksdepartementet og regionens offisielle kilder før du bestiller." },
    ],
  },
  {
    slug: "beirut-ankomst-og-praktisk",
    title: "Beirut: ankomst og det praktiske",
    deck: "Flyplassen ligger nær byen. Det som krever litt planlegging, er papirene og hjemreisen.",
    tags: ["midtosten", "forste-gang"],
    updated: "2026-09-07",
    hero: "beirut",
    relatedDestinations: ["beirut"],
    relatedArticles: ["passet-gyldighet-og-barn", "forsinket-eller-innstilt"],
    searchIata: "BEY",
    blocks: [
      { t: "p", text: "Beirut Rafic Hariri (BEY) ligger sør for sentrum, og turen inn til byen er kort utenom rushtiden. De fleste fra Norge flyr via Istanbul, Wien, Frankfurt eller Paris." },
      { t: "h2", id: "for", text: "Før avreise" },
      { t: "ul", items: [
        "Sjekk Utenriksdepartementets reiseinformasjon for Libanon. Rådene kan endre seg raskt, og forsikringen din kan avhenge av dem.",
        "Innreisereglene bestemmes av libanesiske myndigheter. Ambassaden gir det endelige svaret på hva som gjelder for ditt pass.",
        "Har du stempler eller visum fra enkelte andre land i passet, kan det ha betydning for innreise. Undersøk før du bestiller.",
      ] },
      { t: "h2", id: "ankomst", text: "Ved ankomst" },
      { t: "p", text: "Passkontrollen kan ta tid når flere fly lander samtidig. Taxi fra flyplassen bør avtales i pris før dere setter dere inn, eller bestilles gjennom hotell eller familie. Har noen mulighet til å hente dere, er det det enkleste." },
      { t: "h2", id: "hjem", text: "Hjemreisen" },
      { t: "p", text: "Vær ute i god tid til hjemreisen; sikkerhetskontrollene er grundige, og det er flere av dem. Sjekk hvilke regler som gjelder for elektronikk og væsker på flyplassen du reiser fra, ikke bare de norske." },
      { t: "tip", text: "Meld deg på flyvarsler i profilen, så får du beskjed på e-post hvis flyselskapet endrer tider." },
    ],
  },
  {
    slug: "marokko-casablanca-eller-marrakech",
    title: "Marokko: Casablanca eller Marrakech?",
    deck: "To flyplasser, to helt forskjellige reiser. Velg etter hvor du skal, ikke etter navnet.",
    tags: ["forste-gang", "familie"],
    updated: "2026-09-07",
    hero: "marrakech",
    relatedDestinations: ["marrakech"],
    relatedArticles: ["reise-hjem-til-hoytidene", "reiser-du-alene-med-barn"],
    searchIata: "RAK",
    blocks: [
      { t: "p", text: "Casablanca (CMN) er landets største flyplass og knutepunktet for reiser til resten av Marokko. Marrakech (RAK) er flyplassen for byen og området rundt. Fra Norge går de fleste reisene via Paris, Madrid, Lisboa, Brussel eller Istanbul." },
      { t: "h2", id: "velg", text: "Slik velger du" },
      { t: "ul", items: [
        "Skal du til Casablanca, Rabat eller nordover: Casablanca.",
        "Skal du til Marrakech eller sørover: Marrakech, som regel.",
        "Skal du reise videre innenlands med fly: Casablanca har flest innenlandsruter.",
        "Skal du ta tog: Casablanca har god togforbindelse til flere byer.",
      ] },
      { t: "h2", id: "familie", text: "Med familie" },
      { t: "p", text: "Reisene tar ofte en hel dag med ett bytte. Velg «Familievennlig» i søket for å få kortere ventetid og ingen flyplassbytte først. Ankomst om natten med barn er sjelden verdt en liten prisforskjell." },
      { t: "h2", id: "papirer", text: "Papirer" },
      { t: "p", text: "Sjekk innreisereglene hos Utenriksdepartementet og Marokkos ambassade før du bestiller. Reiser du alene med barn, ta med samtykke fra den andre forelderen; det blir spurt om oftere enn folk tror." },
      { t: "tip", text: "Sett en prisovervåking på begge flyplassene hvis datoene er fleksible. Vi sier fra når noe passer." },
    ],
  },
  {
    slug: "mellomlanding-i-gulfen",
    title: "Mellomlanding i Gulfen på vei til Asia",
    deck: "Dubai, Doha og Abu Dhabi er bygget for bytter. Slik får du mest ut av dem, med og uten barn.",
    tags: ["mellomlanding", "midtosten"],
    updated: "2026-09-07",
    hero: "dubai",
    relatedDestinations: ["dubai", "islamabad", "delhi", "dhaka", "colombo"],
    relatedArticles: ["lang-flytur-med-familien", "mellomlanding-med-barn"],
    searchIata: "DXB",
    blocks: [
      { t: "p", text: "Mange av reisene til Islamabad, Delhi, Dhaka og Colombo går via Gulfen. Flyplassene der er store, effektive og åpne hele natten. Det gjør dem gode for bytter, og utmattende hvis mellomlandingen er lang." },
      { t: "h2", id: "lengde", text: "Hvor lang mellomlanding?" },
      { t: "p", text: "Med én billett gjennom hele reisen tar flyselskapet ansvar for at du rekker neste fly, også med kort tid mellom. Med barn er halvannen til tre timer behagelig. Blir det lenger enn seks–sju timer, vurder om en annen avgang gir bedre søvn totalt sett, selv om den koster litt mer." },
      { t: "h2", id: "bagasje", text: "Bagasjen" },
      { t: "p", text: "Med én billett sendes bagasjen som regel helt fram. Sjekk lappen du får ved innsjekk: står sluttdestinasjonen der, kan du gå rett til neste gate. Er reisen satt sammen av to billetter, må du hente og sjekke inn på nytt, og du trenger tid til det." },
      { t: "h2", id: "ut", text: "Ut av flyplassen?" },
      { t: "p", text: "Ved lange mellomlandinger er det fristende å se byen. Sjekk om det krever visum for ditt pass, og regn med at passkontroll og sikkerhet tar tid begge veier. Med barn og bagasje er en stille krok i terminalen ofte det beste." },
      { t: "tip", text: "Fyll vannflaskene etter sikkerhetskontrollen og hold på håndbagasjen med pass, medisiner og ladere. Alt annet kan vente til dere er framme." },
    ],
  },
];
