/** ISO 3166-1 alpha-2 landkoder for pass-utstederland (norske navn). Norden først. */
export const COUNTRIES: { code: string; name: string }[] = [
  { code: "NO", name: "Norge" },
  { code: "SE", name: "Sverige" },
  { code: "DK", name: "Danmark" },
  { code: "FI", name: "Finland" },
  { code: "IS", name: "Island" },
  { code: "AF", name: "Afghanistan" },
  { code: "AL", name: "Albania" },
  { code: "DZ", name: "Algerie" },
  { code: "AR", name: "Argentina" },
  { code: "AM", name: "Armenia" },
  { code: "AU", name: "Australia" },
  { code: "AT", name: "Østerrike" },
  { code: "AZ", name: "Aserbajdsjan" },
  { code: "BH", name: "Bahrain" },
  { code: "BD", name: "Bangladesh" },
  { code: "BE", name: "Belgia" },
  { code: "BA", name: "Bosnia-Hercegovina" },
  { code: "BR", name: "Brasil" },
  { code: "BG", name: "Bulgaria" },
  { code: "CA", name: "Canada" },
  { code: "CL", name: "Chile" },
  { code: "CN", name: "Kina" },
  { code: "CO", name: "Colombia" },
  { code: "HR", name: "Kroatia" },
  { code: "CY", name: "Kypros" },
  { code: "CZ", name: "Tsjekkia" },
  { code: "EG", name: "Egypt" },
  { code: "EE", name: "Estland" },
  { code: "ET", name: "Etiopia" },
  { code: "FR", name: "Frankrike" },
  { code: "GE", name: "Georgia" },
  { code: "DE", name: "Tyskland" },
  { code: "GH", name: "Ghana" },
  { code: "GR", name: "Hellas" },
  { code: "HU", name: "Ungarn" },
  { code: "IN", name: "India" },
  { code: "ID", name: "Indonesia" },
  { code: "IR", name: "Iran" },
  { code: "IQ", name: "Irak" },
  { code: "IE", name: "Irland" },
  { code: "IL", name: "Israel" },
  { code: "IT", name: "Italia" },
  { code: "JP", name: "Japan" },
  { code: "JO", name: "Jordan" },
  { code: "KZ", name: "Kasakhstan" },
  { code: "KE", name: "Kenya" },
  { code: "KR", name: "Sør-Korea" },
  { code: "KW", name: "Kuwait" },
  { code: "LV", name: "Latvia" },
  { code: "LB", name: "Libanon" },
  { code: "LT", name: "Litauen" },
  { code: "LU", name: "Luxembourg" },
  { code: "MY", name: "Malaysia" },
  { code: "MT", name: "Malta" },
  { code: "MX", name: "Mexico" },
  { code: "MD", name: "Moldova" },
  { code: "ME", name: "Montenegro" },
  { code: "MA", name: "Marokko" },
  { code: "NL", name: "Nederland" },
  { code: "NZ", name: "New Zealand" },
  { code: "NG", name: "Nigeria" },
  { code: "MK", name: "Nord-Makedonia" },
  { code: "PK", name: "Pakistan" },
  { code: "PE", name: "Peru" },
  { code: "PH", name: "Filippinene" },
  { code: "PL", name: "Polen" },
  { code: "PT", name: "Portugal" },
  { code: "QA", name: "Qatar" },
  { code: "RO", name: "Romania" },
  { code: "RU", name: "Russland" },
  { code: "SA", name: "Saudi-Arabia" },
  { code: "RS", name: "Serbia" },
  { code: "SG", name: "Singapore" },
  { code: "SK", name: "Slovakia" },
  { code: "SI", name: "Slovenia" },
  { code: "SO", name: "Somalia" },
  { code: "ZA", name: "Sør-Afrika" },
  { code: "ES", name: "Spania" },
  { code: "LK", name: "Sri Lanka" },
  { code: "SY", name: "Syria" },
  { code: "CH", name: "Sveits" },
  { code: "TW", name: "Taiwan" },
  { code: "TH", name: "Thailand" },
  { code: "TN", name: "Tunisia" },
  { code: "TR", name: "Tyrkia" },
  { code: "UA", name: "Ukraina" },
  { code: "AE", name: "De forente arabiske emirater" },
  { code: "GB", name: "Storbritannia" },
  { code: "US", name: "USA" },
  { code: "VN", name: "Vietnam" },
];

/** Vanlige landskoder for telefon. */
export const PHONE_CODES: { code: string; label: string }[] = [
  { code: "+47", label: "Norge (+47)" },
  { code: "+46", label: "Sverige (+46)" },
  { code: "+45", label: "Danmark (+45)" },
  { code: "+358", label: "Finland (+358)" },
  { code: "+354", label: "Island (+354)" },
  { code: "+44", label: "Storbritannia (+44)" },
  { code: "+49", label: "Tyskland (+49)" },
  { code: "+48", label: "Polen (+48)" },
  { code: "+31", label: "Nederland (+31)" },
  { code: "+33", label: "Frankrike (+33)" },
  { code: "+34", label: "Spania (+34)" },
  { code: "+39", label: "Italia (+39)" },
  { code: "+90", label: "Tyrkia (+90)" },
  { code: "+964", label: "Irak (+964)" },
  { code: "+98", label: "Iran (+98)" },
  { code: "+1", label: "USA/Canada (+1)" },
  { code: "+971", label: "Emiratene (+971)" },
  { code: "+92", label: "Pakistan (+92)" },
  { code: "+91", label: "India (+91)" },
  { code: "+66", label: "Thailand (+66)" },
];
