/**
 * ISO 3166-1 alpha-2 → norsk landnavn.
 *
 * Brukes både i nettleseren (passutstederland i kassen) og på serveren
 * (flyplassregisteret fra OurAirports, som oppgir landnavn på engelsk).
 * Listen dekker landene HelloSky faktisk flyr til og fra. Mangler et land,
 * beholder vi kildens eget navn i stedet for å gjette.
 */
export const COUNTRY_NB: Record<string, string> = {
  NO: "Norge",
  SE: "Sverige",
  DK: "Danmark",
  FI: "Finland",
  IS: "Island",
  AF: "Afghanistan",
  AL: "Albania",
  DZ: "Algerie",
  AR: "Argentina",
  AM: "Armenia",
  AU: "Australia",
  AT: "Østerrike",
  AZ: "Aserbajdsjan",
  BH: "Bahrain",
  BD: "Bangladesh",
  BE: "Belgia",
  BA: "Bosnia-Hercegovina",
  BR: "Brasil",
  BG: "Bulgaria",
  CA: "Canada",
  CL: "Chile",
  CN: "Kina",
  CO: "Colombia",
  HR: "Kroatia",
  CY: "Kypros",
  CZ: "Tsjekkia",
  EG: "Egypt",
  EE: "Estland",
  ET: "Etiopia",
  FR: "Frankrike",
  GE: "Georgia",
  DE: "Tyskland",
  GH: "Ghana",
  GR: "Hellas",
  HU: "Ungarn",
  IN: "India",
  ID: "Indonesia",
  IR: "Iran",
  IQ: "Irak",
  IE: "Irland",
  IL: "Israel",
  IT: "Italia",
  JP: "Japan",
  JO: "Jordan",
  KZ: "Kasakhstan",
  KE: "Kenya",
  KR: "Sør-Korea",
  KW: "Kuwait",
  LV: "Latvia",
  LB: "Libanon",
  LT: "Litauen",
  LU: "Luxembourg",
  MY: "Malaysia",
  MT: "Malta",
  MX: "Mexico",
  MD: "Moldova",
  ME: "Montenegro",
  MA: "Marokko",
  NL: "Nederland",
  NZ: "New Zealand",
  NG: "Nigeria",
  MK: "Nord-Makedonia",
  PK: "Pakistan",
  PE: "Peru",
  PH: "Filippinene",
  PL: "Polen",
  PT: "Portugal",
  QA: "Qatar",
  RO: "Romania",
  RU: "Russland",
  SA: "Saudi-Arabia",
  RS: "Serbia",
  SG: "Singapore",
  SK: "Slovakia",
  SI: "Slovenia",
  SO: "Somalia",
  ZA: "Sør-Afrika",
  ES: "Spania",
  LK: "Sri Lanka",
  SY: "Syria",
  CH: "Sveits",
  TW: "Taiwan",
  TH: "Thailand",
  TN: "Tunisia",
  TR: "Tyrkia",
  UA: "Ukraina",
  AE: "De forente arabiske emirater",
  GB: "Storbritannia",
  US: "USA",
  VN: "Vietnam",
};

/** Norsk landnavn når vi har det, ellers navnet kilden oppga. */
export function countryName(code: string, fallback: string): string {
  return COUNTRY_NB[code.toUpperCase()] ?? fallback;
}
